# Generated by Django 5.2.17 on 2026-09-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.paciente')),
            ],
        ),
    ]
